tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "coreutils"
brew "git-lfs"
brew "gnu-sed"
brew "grep"
brew "mas"
brew "pkg-config"
brew "watch"
brew "watchman"
# brew "mysql"

brew "tmux"
brew "fd"
brew "ripgrep"

brew "node"
brew "python"

cask "iterm2"

brew "neovim", args: ["HEAD"]
cask "sublime-text"
cask "visual-studio-code"

cask "firefox"
cask "google-chrome"

cask "docker"
cask "rectangle"

mas "1Password 7 - Password Manager", id: 1333542190
